<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testCases.ComponentCode_Employer_TestCases" tests="1" time="38.604" ignored="8" failures="1" timestamp="01 May 2019 19:15:23 GMT" skipped="0" hostname="LH7U05CG6272CBT" errors="0">
  <testcase name="TC_EMP_Insert_Chart_ANOC" time="38.604" classname="testCases.ComponentCode_Employer_TestCases">
    <failure type="java.lang.AssertionError" message="upload file was unsuccessful">
      <![CDATA[java.lang.AssertionError: upload file was unsuccessful
	at org.testng.Assert.fail(Assert.java:94)
	at actions.Actions_ComponentCodePage.uploadFile_inPopUp(Actions_ComponentCodePage.java:64)
	at testCases.ComponentCode_Employer_TestCases.TC_EMP_Insert_Chart_ANOC(ComponentCode_Employer_TestCases.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- TC_EMP_Insert_Chart_ANOC -->
  <testcase name="TC_EMP_ErrorMessage_InvalidPlanData" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_ErrorMessage_InvalidPlanData -->
  <testcase name="TC_EMP_ErrorMessage_Max30Chars" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_ErrorMessage_Max30Chars -->
  <testcase name="TC_EMP_Update_Chart_ANOC" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_Update_Chart_ANOC -->
  <testcase name="TC_EMP_Search_Chart" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_Search_Chart -->
  <testcase name="TC_EMP_Search_Anoc" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_Search_Anoc -->
  <testcase name="TC_EMP_ErrorMessage_Min4Chars" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_ErrorMessage_Min4Chars -->
  <testcase name="TC_EMP_Delete_Chart_ANOC" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_Delete_Chart_ANOC -->
  <testcase name="TC_EMP_ErrorMessage_InvalidPlanYear" classname="testCases.ComponentCode_Employer_TestCases">
    <skipped/>
  </testcase> <!-- TC_EMP_ErrorMessage_InvalidPlanYear -->
</testsuite> <!-- testCases.ComponentCode_Employer_TestCases -->
